name: Upload ZIP on Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create flat ZIP with selected files
        run: |
          zip -r release.zip README.md LICENSE

      - name: Create Release and Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: FunctionBook.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
